
const state = {
  page: "dashboard",
  user: JSON.parse(localStorage.getItem("sga_user") || "null"),
  checklist: JSON.parse(localStorage.getItem("sga_checklist") || "{}"),
  occurrences: JSON.parse(localStorage.getItem("sga_occurrences") || "null") || [
    {id:"OS-2026-0041",env:"Sala de Aula 101",item:"Ar-condicionado",priority:"Alta",status:"Em atendimento",desc:"Liga, mas não refrigera. Apresenta ruído elevado.",date:"28/08/2026"},
    {id:"OS-2026-0040",env:"Laboratório de Química",item:"Iluminação",priority:"Média",status:"Aberta",desc:"Duas luminárias sem funcionamento.",date:"28/08/2026"},
    {id:"OS-2026-0038",env:"Laboratório de Informática 01",item:"PC-03",priority:"Crítica",status:"Aguardando material",desc:"Equipamento não inicializa.",date:"27/08/2026"}
  ]
};

const systemUsers = JSON.parse(localStorage.getItem("sga_users") || "null") || [
  {name:"Ana Paula",role:"Administrador",status:"Ativo",email:"ana.paula@sga.local"},
  {name:"Carlos Silva",role:"Gestor",status:"Ativo",email:"carlos.silva@sga.local"},
  {name:"Marcos Lima",role:"Responsável pelo ambiente",status:"Ativo",email:"marcos.lima@sga.local"},
  {name:"João Souza",role:"Manutenção",status:"Ativo",email:"joao.souza@sga.local"},
  {name:"Equipe Almoxarifado",role:"Almoxarifado",status:"Ativo",email:"almoxarifado@sga.local"},
  {name:"Auditoria",role:"Consulta/Auditoria",status:"Ativo",email:"auditoria@sga.local"}
];

const modules = [
  {id:1,name:"Sala de Aula",items:["Ar-condicionado","Data show / projetor","Carteiras","Mesa do professor","Quadro branco","Iluminação","Cortinas","Kit multimídia","Adaptador de vídeo"]},
  {id:2,name:"Laboratórios",items:["Ar-condicionado","Data show / projetor","Carteiras","Mesa do professor","Quadro branco","Iluminação","Cortinas","Kit multimídia","Adaptador de vídeo","EPI","Equipamentos patrimoniados","Materiais didáticos","Ferramentas"]},
  {id:3,name:"Laboratório de Informática",items:["Ar-condicionado","Data show / projetor","Carteiras","Mesa do professor","Quadro branco","Iluminação","Cortinas","Kit multimídia","Adaptador de vídeo","Computadores","Monitores","Teclados","Mouses","Estabilizadores / nobreaks","Switches","Roteadores","Impressoras","Pontos de rede","Acesso à internet","Softwares essenciais"]},
  {id:4,name:"Manutenção",items:["Ocorrências de manutenção","Ordens de serviço","Peças e materiais utilizados"]},
  {id:5,name:"Almoxarifado",items:["Equipamentos","Ferramentas","Equipamentos patrimoniados","Materiais de consumo","EPIs","Peças utilizadas em manutenção"]}
];

const environments = [
  {code:"SA-101",name:"Sala de Aula 101",module:"Sala de Aula",block:"Bloco A",capacity:40,responsible:"Responsável do ambiente",period:"Semanal",active:true},
  {code:"LAB-Q",name:"Laboratório de Química",module:"Laboratórios",block:"Bloco B",capacity:25,responsible:"Responsável do ambiente",period:"Semanal",active:true},
  {code:"LAB-INF-01",name:"Laboratório de Informática 01",module:"Laboratório de Informática",block:"Bloco C",capacity:30,responsible:"Responsável do ambiente",period:"Diária",active:true},
  {code:"OF-MAN",name:"Oficina de Manutenção",module:"Manutenção",block:"Bloco D",capacity:12,responsible:"Equipe de Manutenção",period:"Mensal",active:true},
  {code:"ALM-01",name:"Almoxarifado Central",module:"Almoxarifado",block:"Bloco E",capacity:0,responsible:"Almoxarifado",period:"Semanal",active:true}
];

const checklistSchedules = JSON.parse(localStorage.getItem("sga_checklist_schedules") || "null") || environments.map(environment=>({environmentCode:environment.code,active:true}));
const checklistExecutions = JSON.parse(localStorage.getItem("sga_checklist_executions") || "[]");

const stock = [
  {code:"EST-001",item:"Lâmpada LED 18W",cat:"Material de consumo",qty:8,min:10,unit:"un",loc:"Prateleira A1",status:"Baixo"},
  {code:"EPI-002",item:"Óculos de proteção",cat:"EPI",qty:42,min:20,unit:"un",loc:"Prateleira B2",status:"Normal"},
  {code:"FER-014",item:"Furadeira",cat:"Ferramenta",qty:3,min:2,unit:"un",loc:"Armário C1",status:"Normal"},
  {code:"MAT-020",item:"Cabo HDMI",cat:"Material de consumo",qty:4,min:5,unit:"un",loc:"Prateleira A3",status:"Baixo"},
  {code:"PAT-031",item:"Notebook Patrimônio 031",cat:"Patrimoniado",qty:1,min:0,unit:"un",loc:"LAB-INF-01",status:"Normal"}
];

const loanRecords = JSON.parse(localStorage.getItem("sga_loans") || "null") || [
  {item:"Furadeira",quantity:"1",withdrawal:"26/08/2026",due:"29/08/2026",returnDate:"—",responsible:"João Souza",status:"Ativo"},
  {item:"Kit de ferramentas",quantity:"1",withdrawal:"20/08/2026",due:"25/08/2026",returnDate:"—",responsible:"Carlos Silva",status:"Atrasado"},
  {item:"Notebook Patrimônio 031",quantity:"1",withdrawal:"27/08/2026",due:"30/08/2026",returnDate:"—",responsible:"Marcos Lima",status:"Ativo"}
];

function save(){localStorage.setItem("sga_user",JSON.stringify(state.user));localStorage.setItem("sga_checklist",JSON.stringify(state.checklist));localStorage.setItem("sga_occurrences",JSON.stringify(state.occurrences));localStorage.setItem("sga_users",JSON.stringify(systemUsers));localStorage.setItem("sga_checklist_schedules",JSON.stringify(checklistSchedules));localStorage.setItem("sga_loans",JSON.stringify(loanRecords));localStorage.setItem("sga_checklist_executions",JSON.stringify(checklistExecutions))}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function badge(v){let c=["Conforme","Concluída","Validada","Normal","Encerrada"].includes(v)?"success":["Alta","Aguardando material","Baixo","Pendente"].includes(v)?"warning":["Crítica","Não conforme","Cancelada"].includes(v)?"danger":["Média","Em atendimento","Aberta","Em triagem"].includes(v)?"info":"gray";return `<span class="badge ${c}">${esc(v)}</span>`}
function layout(){
 return `<div class="app"><aside class="sidebar" id="sidebar">
  <div class="brand"><div class="brand-icon">SGA</div><div><h1>SGA-Checklist</h1><small>Gestão de ambientes</small></div></div>
  <div class="nav">
   <div class="group">Principal</div>
   ${nav("dashboard","Painel geral","▦")}
   ${nav("checklist","Execução do checklist","✓")}
   ${nav("history","Histórico de checklists","◷")}
   <div class="group">Cadastros</div>
   ${nav("users","Usuários","♙")}
   ${nav("environments","Ambientes","⌂")}
   ${nav("catalog","Itens de checklist","☷")}
   ${nav("schedule","Programação","◫")}
   <div class="group">Operação</div>
   ${nav("maintenance","Manutenção / OS","⚙")}
   ${nav("stock","Almoxarifado / Estoque","▤")}
   ${nav("loans","Empréstimos","⇄")}
   <div class="group">Gestão</div>
   ${nav("reports","Relatórios e indicadores","▥")}
   ${nav("settings","Configurações e auditoria","⚑")}
  </div>
 </aside><main class="main"><header class="topbar"><button class="menu" onclick="toggleMenu()">☰</button><div><strong>SGA-Checklist</strong></div><div class="user"><div><strong>${esc(state.user?.name||"Usuário")}</strong><br><small style="color:#6b7785">${esc(state.user?.role||"Administrador")}</small></div><div class="avatar">${(state.user?.name||"U").slice(0,1).toUpperCase()}</div><button class="btn" onclick="logout()">Sair</button></div></header><section class="content" id="content"></section></main></div>
 <div class="modal-backdrop" id="modal"></div>`;
}
function nav(id,label,icon){return `<button class="${state.page===id?'active':''}" onclick="go('${id}')">${icon} &nbsp; ${label}</button>`}
function toggleMenu(){document.getElementById("sidebar").classList.toggle("open")}
function go(p){state.page=p;render();document.getElementById("sidebar")?.classList.remove("open")}
function pageHeader(title,sub,action=""){return `<div class="title"><div><h2>${title}</h2><p>${sub}</p></div>${action}</div>`}

function dashboard(){
 const closedStatuses=["Concluída","Validada","Encerrada","Cancelada"], completedHistory=checklistHistory.filter(row=>row[5]==="Concluída"), conformityValues=completedHistory.map(row=>Number.parseFloat(row[4])).filter(Number.isFinite), conformity=conformityValues.length?`${Math.round(conformityValues.reduce((total,value)=>total+value,0)/conformityValues.length)}%`:"0%";
 const open=state.occurrences.filter(x=>!closedStatuses.includes(x.status)).length, critical=state.occurrences.filter(x=>x.priority==="Crítica"&&!closedStatuses.includes(x.status)).length, overdueLoans=loanRecords.filter(loan=>loan.status==="Atrasado").length, lowStock=stock.filter(item=>item.qty<item.min).length;
 return pageHeader("Painel geral","Visão consolidada de checklists, manutenção e estoque.",`<button class="btn primary" onclick="go('checklist')">+ Executar checklist</button>`)
 +`<div class="grid kpis">
 ${kpi("Checklists programados",checklistSchedules.length,"◫")} ${kpi("Checklists concluídos",completedHistory.length,"✓")} ${kpi("Checklists atrasados",checklistHistory.filter(row=>row[5]==="Atrasado").length,"!")} ${kpi("Taxa de conformidade",conformity,"%")}
 ${kpi("Ocorrências abertas",open,"⚙")} ${kpi("Ocorrências críticas",critical,"!")} ${kpi("Estoque baixo",lowStock,"▤")} ${kpi("Empréstimos atrasados",overdueLoans,"⇄")}
 </div>
 <div class="grid two" style="margin-top:18px">
  <div class="card"><h3>Conformidade por módulo</h3><div class="list">
   ${barLine("Sala de Aula",96)}${barLine("Laboratórios",89)}${barLine("Informática",93)}${barLine("Manutenção",87)}${barLine("Almoxarifado",91)}
  </div></div>
  <div class="card"><h3>Alertas prioritários</h3><div class="list">
   ${alertLine("Ocorrência crítica","LAB-INF-01 • PC-03","Crítica")}
   ${alertLine("Estoque abaixo do mínimo","Lâmpada LED 18W","Baixo")}
   ${alertLine("Checklist atrasado","Sala de Aula 104","Atrasado")}
   ${alertLine("Prazo próximo","OS-2026-0041","Alta")}
  </div></div>
 </div>
 <div class="grid two" style="margin-top:18px">
  <div class="card"><h3>Ocorrências recentes</h3>${occurrenceTable(state.occurrences.slice(0,4))}</div>
  <div class="card"><h3>Programação da semana</h3><div class="chart">${[65,80,55,92,70,45,30].map((v,i)=>`<div class="bar"><i style="height:${v*1.7}px"></i><span>${["Seg","Ter","Qua","Qui","Sex","Sáb","Dom"][i]}</span></div>`).join("")}</div></div>
 </div>`;
}
function kpi(label,value,icon){return `<div class="card kpi"><div><div class="label">${label}</div><div class="value">${value}</div></div><div class="icon">${icon}</div></div>`}
function barLine(name,val){return `<div class="list-item"><div style="width:35%">${name}</div><div style="flex:1"><div class="progress"><i style="width:${val}%"></i></div></div><strong>${val}%</strong></div>`}
function alertLine(a,b,c){return `<div class="list-item"><div><strong>${a}</strong><br><small style="color:#6b7785">${b}</small></div>${badge(c)}</div>`}

function checklistPage(){
 let env=environments.find(e=>e.code===state._env)||environments[0], mod=modules.find(m=>m.name===env.module)||modules[0];
 let key=env.code, data=state.checklist[key]||{}, period=env.period, executionDate=state._checkDate||"2026-08-28", weeklyExecution=checklistExecutions.find(execution=>execution.environmentCode===key&&execution.period===period&&weekKey(execution.executionDate)===weekKey(executionDate)), action=weeklyExecution?`<button class="btn success" onclick="confirmWeeklyChecklist('${key}')" ${weeklyExecution.confirmedAt?"disabled":""}>${weeklyExecution.confirmedAt?"Checklist confirmado":"Confirmar checklist da semana"}</button>`:`<button class="btn success" onclick="finishChecklist('${key}')">Finalizar checklist</button>`;
 return pageHeader("Execução do checklist","Preencha todos os itens. Observação é obrigatória para situações irregulares.",action)
 +`<div class="card" style="margin-bottom:18px"><div class="toolbar">
  <select class="select" id="envSel" onchange="loadChecklist(this.value)">${environments.map(e=>`<option value="${e.code}" ${e.code===key?'selected':''}>${e.name}</option>`).join("")}</select>
  <select class="select" id="periodSel"><option>Diária</option><option selected>Semanal</option><option>Mensal</option></select>
  <input class="input" id="checkDate" type="date" value="${executionDate}" onchange="setChecklistDate(this.value)">
  <span style="align-self:center">${badge("Em preenchimento")}</span>
 </div></div>
 <div class="grid two"><div>${mod.items.map((item,i)=>checkItem(item,i,key,data[item]||{})).join("")}</div>
 <div><div class="card"><h3>Resumo</h3><div class="list">
  ${summaryLine("Itens",mod.items.length)}${summaryLine("Respondidos",Object.keys(data).length)}${summaryLine("Conformes",Object.values(data).filter(x=>x.status==="Conforme").length)}${summaryLine("Não conformes",Object.values(data).filter(x=>x.status==="Não conforme").length)}
 </div></div><div class="alert" style="margin-top:14px"><strong>Regra:</strong> itens “Parcialmente conforme”, “Não conforme” ou “Não verificado” exigem observação.</div></div></div>`;
}
function loadChecklist(code){state._env=code;render()}
function checkItem(item,i,key,data){
 let status=data.status||"";
 return `<div class="check-item"><div class="check-head"><div><div class="check-name">${esc(item)}</div><div class="check-meta">Item ${i+1} • ambiente designado</div></div>${status?badge(status):badge("Pendente")}</div>
 <div class="status-options">${["Conforme","Parcialmente conforme","Não conforme","Não se aplica","Não verificado"].map(s=>`<button class="${status===s?'selected':''}" onclick="setCheck('${key}',${esc(JSON.stringify(item))},'${s}')">${s}</button>`).join("")}</div>
 ${["Parcialmente conforme","Não conforme","Não verificado"].includes(status)?`<label class="check-observation-label" for="obs-${key}-${i}">Descrição da não conformidade *</label><textarea class="textarea obs" id="obs-${key}-${i}" required placeholder="Descreva a não conformidade (obrigatório)" oninput="setObs('${key}',${esc(JSON.stringify(item))},this.value)">${esc(data.obs||"")}</textarea>`:""}
 </div>`;
}
function setCheck(key,item,status){state.checklist[key]??={};let current=state.checklist[key][item]||{};state.checklist[key][item]={...current,status};save();render()}
function setObs(key,item,obs){state.checklist[key][item]={...(state.checklist[key][item]||{}),obs};save()}
function summaryLine(a,b){return `<div class="list-item"><span>${a}</span><strong>${b}</strong></div>`}
function weekKey(dateValue){let date=new Date(`${dateValue}T00:00:00Z`);if(Number.isNaN(date.getTime()))return "";let day=date.getUTCDay()||7;date.setUTCDate(date.getUTCDate()+4-day);let year=date.getUTCFullYear(),yearStart=new Date(Date.UTC(year,0,1));return `${year}-W${String(Math.ceil((((date-yearStart)/86400000)+1)/7)).padStart(2,"0")}`}
function setChecklistDate(dateValue){state._checkDate=dateValue;render()}
function confirmWeeklyChecklist(key){let execution=checklistExecutions.find(item=>item.environmentCode===key&&weekKey(item.executionDate)===weekKey(state._checkDate||"2026-08-28"));if(!execution)return;execution.confirmedAt=execution.confirmedAt||new Date().toISOString();save();alert("Checklist da semana confirmado.");render()}
function finishChecklist(key){
 let data=state.checklist[key]||{}, env=environments.find(e=>e.code===key)||environments[0], mod=modules.find(m=>m.name===env.module)||modules[0];
 let period=document.getElementById("periodSel")?.value||env.period, executionDate=document.getElementById("checkDate")?.value||"2026-08-28";
 if(checklistExecutions.some(execution=>execution.environmentCode===key&&execution.period===period&&weekKey(execution.executionDate)===weekKey(executionDate))){alert("Este ambiente já possui um checklist nesta semana.");return}
 if(Object.keys(data).length<mod.items.length){alert("Não é possível concluir: existem itens sem resposta.");return}
 let bad=Object.entries(data).filter(([_,x])=>["Parcialmente conforme","Não conforme","Não verificado"].includes(x.status)&&!x.obs?.trim());
 if(bad.length){alert("Existem itens irregulares sem observação.");return}
 Object.entries(data).forEach(([item,x])=>{if(x.status==="Não conforme"||x.status==="Parcialmente conforme"){state.occurrences.unshift({id:"OS-2026-"+String(41+state.occurrences.length).padStart(4,"0"),env:env.name,item,priority:"Alta",status:"Aberta",desc:x.obs,date:"28/08/2026"})}});
 checklistExecutions.push({environmentCode:key,period,executionDate,completedAt:new Date().toISOString()});save();alert("Checklist finalizado. Não conformidades foram encaminhadas para Manutenção.");go("history")
}

function occurrenceTable(rows){return `<div class="table-wrap"><table class="table"><thead><tr><th>Chamado</th><th>Ambiente</th><th>Item</th><th>Prioridade</th><th>Situação</th><th>Ação</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${r.id}</strong><br><small>${r.date}</small></td><td>${esc(r.env)}</td><td>${esc(r.item)}</td><td>${badge(r.priority)}</td><td>${badge(r.status)}</td><td><button class="btn" onclick="openOccurrenceEdit('${r.id}')">Editar OS</button></td></tr>`).join("")}</tbody></table></div>`}
function openOccurrenceEdit(id){let occurrence=state.occurrences.find(item=>item.id===id);if(!occurrence)return;showModal(`<div class="modal-head"><h3>Editar ${esc(occurrence.id)}</h3><button class="close" onclick="closeModal()">✕</button></div><div class="form-grid"><div class="field"><label>Ambiente</label><input class="input" value="${esc(occurrence.env)}" disabled></div><div class="field"><label>Prioridade</label><select class="select" id="editPriority">${["Baixa","Média","Alta","Crítica"].map(value=>`<option ${value===occurrence.priority?"selected":""}>${value}</option>`).join("")}</select></div><div class="field"><label>Situação</label><select class="select" id="editStatus">${["Aberta","Em triagem","Em atendimento","Aguardando material","Concluída","Validada","Encerrada","Cancelada"].map(value=>`<option ${value===occurrence.status?"selected":""}>${value}</option>`).join("")}</select></div><div class="field full"><label>Item</label><input class="input" id="editItem" value="${esc(occurrence.item)}"></div><div class="field full"><label>Descrição</label><textarea class="textarea" id="editDescription">${esc(occurrence.desc)}</textarea></div></div><div style="display:flex;justify-content:flex-end;gap:10px;margin-top:18px"><button class="btn" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveOccurrenceEdit('${occurrence.id}')">Salvar alterações</button></div>`)}
function saveOccurrenceEdit(id){let occurrence=state.occurrences.find(item=>item.id===id);if(!occurrence)return;occurrence.priority=document.getElementById("editPriority").value;occurrence.status=document.getElementById("editStatus").value;occurrence.item=document.getElementById("editItem").value.trim()||"Item não informado";occurrence.desc=document.getElementById("editDescription").value.trim();save();closeModal();render()}

function maintenance(){
 return pageHeader("Manutenção / Ordens de serviço","Ocorrências geradas a partir das não conformidades dos checklists.",`<button class="btn primary" onclick="openOccurrence()">+ Nova ocorrência</button>`)
 +`<div class="card"><div class="toolbar"><input class="input" id="occSearch" placeholder="Pesquisar chamado, ambiente ou item" oninput="filterOcc()"><select class="select" id="occPriority" onchange="filterOcc()"><option value="">Todas prioridades</option><option>Baixa</option><option>Média</option><option>Alta</option><option>Crítica</option></select><select class="select" id="occStatus" onchange="filterOcc()"><option value="">Todas situações</option><option>Aberta</option><option>Em triagem</option><option>Em atendimento</option><option>Aguardando material</option><option>Concluída</option><option>Validada</option><option>Encerrada</option></select></div><div id="occTable">${occurrenceTable(state.occurrences)}</div></div>
 <div class="grid two" style="margin-top:18px"><div class="card"><h3>Fluxo da manutenção</h3><div class="list">${["Checklist realizado","Existe não conformidade?","Abrir ocorrência","Triagem da manutenção","Em atendimento","Aguardando peça ou material","Serviço concluído","Validação do responsável","Ocorrência encerrada"].map((x,i)=>`<div class="list-item"><span>${i+1}. ${x}</span>${i<8?"→":""}</div>`).join("")}</div></div><div class="card"><h3>Indicadores</h3>${barLine("Resolvidas no prazo",82)}${barLine("Dentro do SLA",76)}${barLine("Validadas",91)}</div></div>`;
}
function filterOcc(){let q=(document.getElementById("occSearch")?.value||"").toLowerCase(),p=document.getElementById("occPriority")?.value||"",s=document.getElementById("occStatus")?.value||"";let rows=state.occurrences.filter(r=>(!q||Object.values(r).join(" ").toLowerCase().includes(q))&&(!p||r.priority===p)&&(!s||r.status===s));document.getElementById("occTable").innerHTML=occurrenceTable(rows)}
function openOccurrence(){
 showModal(`<div class="modal-head"><h3>Nova ocorrência</h3><button class="close" onclick="closeModal()">✕</button></div><div class="form-grid">
 <div class="field"><label>Ambiente</label><select class="select" id="fenv">${environments.map(e=>`<option>${e.name}</option>`).join("")}</select></div>
 <div class="field"><label>Prioridade</label><select class="select" id="fprio"><option>Baixa</option><option>Média</option><option selected>Alta</option><option>Crítica</option></select></div>
 <div class="field full"><label>Item</label><input class="input" id="fitem" placeholder="Equipamento, material ou item do checklist"></div>
 <div class="field full"><label>Descrição</label><textarea class="textarea" id="fdesc" placeholder="Descreva a irregularidade"></textarea></div>
 </div><div style="display:flex;justify-content:flex-end;gap:10px;margin-top:18px"><button class="btn" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="createOccurrence()">Salvar ocorrência</button></div>`)
}
function createOccurrence(){let id="OS-2026-"+String(45+state.occurrences.length).padStart(4,"0");state.occurrences.unshift({id,env:document.getElementById("fenv").value,item:document.getElementById("fitem").value||"Item não informado",priority:document.getElementById("fprio").value,status:"Aberta",desc:document.getElementById("fdesc").value,date:"28/08/2026"});save();closeModal();render()}
function showModal(html){document.getElementById("modal").innerHTML=`<div class="modal">${html}</div>`;document.getElementById("modal").classList.add("show")}
function closeModal(){document.getElementById("modal").classList.remove("show")}

function environmentsPage(){return pageHeader("Cadastro de ambientes","Gerencie locais, módulos, responsáveis e periodicidade.",`<button class="btn primary" onclick="openEnvironment()">+ Novo ambiente</button>`)+`<div class="card"><div class="toolbar"><input class="input" placeholder="Pesquisar ambiente..."></div><div class="table-wrap"><table class="table"><thead><tr><th>Código</th><th>Ambiente</th><th>Módulo</th><th>Bloco</th><th>Capacidade</th><th>Periodicidade</th><th>Situação</th></tr></thead><tbody>${environments.map(e=>`<tr><td><strong>${e.code}</strong></td><td>${e.name}</td><td>${e.module}</td><td>${e.block}</td><td>${e.capacity||"—"}</td><td>${e.period}</td><td>${e.active?badge("Ativo"):badge("Inativo")}</td></tr>`).join("")}</tbody></table></div></div>`}
function openEnvironment(){showModal(`<div class="modal-head"><h3>Novo ambiente</h3><button class="close" onclick="closeModal()">✕</button></div><div class="form-grid"><div class="field"><label>Código</label><input class="input" id="ec"></div><div class="field"><label>Nome</label><input class="input" id="en"></div><div class="field"><label>Módulo</label><select class="select" id="em">${modules.map(m=>`<option>${m.name}</option>`).join("")}</select></div><div class="field"><label>Bloco / setor</label><input class="input" id="eb"></div><div class="field"><label>Capacidade</label><input class="input" id="eca" type="number"></div><div class="field"><label>Periodicidade</label><select class="select" id="ep"><option>Diária</option><option>Semanal</option><option>Mensal</option></select></div></div><div style="text-align:right;margin-top:18px"><button class="btn primary" onclick="addEnvironment()">Cadastrar</button></div>`)}
function addEnvironment(){environments.push({code:document.getElementById("ec").value,name:document.getElementById("en").value,module:document.getElementById("em").value,block:document.getElementById("eb").value,capacity:+document.getElementById("eca").value||0,responsible:"",period:document.getElementById("ep").value,active:true});closeModal();render()}

function stockPage(){return pageHeader("Almoxarifado / Estoque","Equipamentos, ferramentas, patrimônio, materiais, EPIs e peças.",`<button class="btn primary" onclick="openStock()">+ Cadastrar item</button>`)+`<div class="grid three" style="margin-bottom:18px">${kpi("Itens cadastrados","128","▤")}${kpi("Estoque baixo",stock.filter(x=>x.qty<x.min).length,"!")}${kpi("Empréstimos ativos","7","⇄")}</div><div class="card"><div class="toolbar"><input class="input" placeholder="Pesquisar item, código ou patrimônio"><select class="select"><option>Todas categorias</option><option>EPI</option><option>Ferramenta</option><option>Patrimoniado</option><option>Material de consumo</option></select><button class="btn">Registrar movimentação</button></div>${stockTable()}</div>`}
function stockTable(){return `<div class="table-wrap"><table class="table"><thead><tr><th>Código</th><th>Item</th><th>Categoria</th><th>Quantidade</th><th>Mínimo</th><th>Localização</th><th>Status</th></tr></thead><tbody>${stock.map(x=>`<tr><td><strong>${x.code}</strong></td><td>${x.item}</td><td>${x.cat}</td><td>${x.qty} ${x.unit}</td><td>${x.min}</td><td>${x.loc}</td><td>${x.qty<x.min?badge("Baixo"):badge("Normal")}</td></tr>`).join("")}</tbody></table></div>`}
function openStock(){showModal(`<div class="modal-head"><h3>Cadastrar item</h3><button class="close" onclick="closeModal()">✕</button></div><div class="form-grid"><div class="field"><label>Código interno</label><input class="input"></div><div class="field"><label>Categoria</label><select class="select"><option>Equipamento</option><option>Ferramenta</option><option>Patrimoniado</option><option>Material de consumo</option><option>EPI</option></select></div><div class="field full"><label>Descrição</label><input class="input"></div><div class="field"><label>Quantidade atual</label><input class="input" type="number"></div><div class="field"><label>Estoque mínimo</label><input class="input" type="number"></div><div class="field"><label>Localização</label><input class="input"></div><div class="field"><label>Número de patrimônio</label><input class="input"></div></div><div style="text-align:right;margin-top:18px"><button class="btn primary" onclick="closeModal()">Cadastrar</button></div>`)}
function usersPage(){return pageHeader("Usuários e permissões","Controle de acesso por perfil e ambientes designados.",`<button class="btn primary" onclick="openUserCreate()">+ Novo usuário</button>`)+`<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Usuário</th><th>Perfil</th><th>Ambientes</th><th>Último acesso</th><th>Situação</th><th>Ações</th></tr></thead><tbody>${systemUsers.map((user,index)=>`<tr><td><strong>${esc(user.name)}</strong><br><small>${esc(user.email)}</small></td><td>${esc(user.role)}</td><td>Designados conforme permissão</td><td>28/08/2026 13:42</td><td>${badge(user.status)}</td><td><button class="btn" onclick="openUserEdit(${index})">Editar</button> <button class="btn" onclick="validateUser(${index})" ${user.status==="Ativo"?"disabled":""}>Validar</button></td></tr>`).join("")}</tbody></table></div></div><div class="grid three" style="margin-top:18px">${["Administrador","Gestor","Responsável pelo ambiente","Manutenção","Almoxarifado","Consulta/Auditoria"].map((role,index)=>`<div class="card"><strong>${role}</strong><p style="color:#6b7785;font-size:12px">${["Configura sistema, usuários e relatórios","Acompanha, aprova e consulta indicadores","Preenche checklists dos locais designados","Recebe, atualiza e encerra ocorrências","Controla estoque, patrimônio e empréstimos","Visualiza registros e relatórios sem editar"][index]}</p></div>`).join("")}</div>`}
function openUserCreate(){showModal(`<div class="modal-head"><h3>Novo usuário</h3><button class="close" onclick="closeModal()">✕</button></div><div class="form-grid"><div class="field"><label>Nome completo</label><input class="input" id="newUserName" required></div><div class="field"><label>E-mail</label><input class="input" id="newUserEmail" type="email" required></div><div class="field"><label>Senha</label><input class="input" id="newUserPassword" type="password" minlength="6" required></div><div class="field"><label>Confirmar senha</label><input class="input" id="newUserPasswordConfirm" type="password" minlength="6" required></div><div class="field"><label>Perfil</label><select class="select" id="newUserRole">${["Administrador","Gestor","Responsável pelo ambiente","Manutenção","Almoxarifado","Consulta/Auditoria"].map(role=>`<option>${role}</option>`).join("")}</select></div><div class="field"><label>Situação inicial</label><select class="select" id="newUserStatus"><option selected>Pendente</option><option>Ativo</option><option>Inativo</option></select></div></div><div style="display:flex;justify-content:flex-end;gap:10px;margin-top:18px"><button class="btn" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="createUser()">Cadastrar usuário</button></div>`)}
function createUser(){let name=document.getElementById("newUserName").value.trim(),email=document.getElementById("newUserEmail").value.trim().toLowerCase(),password=document.getElementById("newUserPassword").value,passwordConfirm=document.getElementById("newUserPasswordConfirm").value,role=document.getElementById("newUserRole").value,status=document.getElementById("newUserStatus").value;if(!name||!email||!password){alert("Preencha nome, e-mail e senha.");return}if(password.length<6){alert("A senha deve ter pelo menos 6 caracteres.");return}if(password!==passwordConfirm){alert("As senhas não coincidem.");return}if(systemUsers.some(user=>user.email.toLowerCase()===email)){alert("Já existe um usuário com este e-mail.");return}systemUsers.push({name,email,role,status,passwordConfigured:true});save();closeModal();render()}
function openUserEdit(index){let user=systemUsers[index];if(!user)return;showModal(`<div class="modal-head"><h3>Editar usuário</h3><button class="close" onclick="closeModal()">✕</button></div><div class="form-grid"><div class="field"><label>Nome</label><input class="input" id="editUserName" value="${esc(user.name)}"></div><div class="field"><label>E-mail</label><input class="input" id="editUserEmail" type="email" value="${esc(user.email)}"></div><div class="field"><label>Perfil</label><select class="select" id="editUserRole">${["Administrador","Gestor","Responsável pelo ambiente","Manutenção","Almoxarifado","Consulta/Auditoria"].map(role=>`<option ${role===user.role?"selected":""}>${role}</option>`).join("")}</select></div><div class="field"><label>Situação</label><select class="select" id="editUserStatus"><option ${user.status==="Ativo"?"selected":""}>Ativo</option><option ${user.status==="Pendente"?"selected":""}>Pendente</option><option ${user.status==="Inativo"?"selected":""}>Inativo</option></select></div></div><div style="display:flex;justify-content:flex-end;gap:10px;margin-top:18px"><button class="btn" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveUserEdit(${index})">Salvar alterações</button></div>`)}
function saveUserEdit(index){let user=systemUsers[index];if(!user)return;user.name=document.getElementById("editUserName").value.trim()||user.name;user.email=document.getElementById("editUserEmail").value.trim();user.role=document.getElementById("editUserRole").value;user.status=document.getElementById("editUserStatus").value;save();closeModal();render()}
function validateUser(index){let user=systemUsers[index];if(!user)return;user.status="Ativo";save();render()}
function catalogPage(){return pageHeader("Itens de checklist","Catálogo configurável no banco para permitir evolução sem alterar o código.",`<button class="btn primary">+ Novo item</button>`)+`<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Item</th><th>Módulo</th><th>Tipo</th><th>Quantidade</th><th>Evidência</th><th>Ativo</th></tr></thead><tbody>${modules.flatMap(m=>m.items.slice(0, m.id===3?8:5).map(item=>`<tr><td>${item}</td><td>${m.name}</td><td>Equipamento / item</td><td>Configurável</td><td>Opcional / conforme regra</td><td>${badge("Ativo")}</td></tr>`)).join("")}</tbody></table></div></div>`}
const checklistHistory = [["28/08/2026","Sala de Aula 101","Semanal","Marcos Lima","96%","Concluída"],["27/08/2026","LAB-INF-01","Diária","Marcos Lima","93%","Concluída"],["25/08/2026","Laboratório de Química","Semanal","Marcos Lima","89%","Concluída"],["22/08/2026","Sala de Aula 104","Semanal","Marcos Lima","—","Atrasado"]];
function downloadExcelTable(rows,filename){let table=`<table border="1"><thead><tr>${rows[0].map(value=>`<th>${esc(value)}</th>`).join("")}</tr></thead><tbody>${rows.slice(1).map(row=>`<tr>${row.map(value=>`<td>${esc(value)}</td>`).join("")}</tr>`).join("")}</tbody></table>`,html=`<html><head><meta charset="utf-8"><style>table{border-collapse:collapse;font-family:Calibri,Arial}th{background:#0f4c81;color:white;font-weight:bold}th,td{padding:7px;border:1px solid #b8c4d1}</style></head><body>${table}</body></html>`,blob=new Blob(["\ufeff"+html],{type:"application/vnd.ms-excel;charset=utf-8;"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url)}
function downloadChecklistReport(index){let row=checklistHistory[index];if(!row)return;downloadExcelTable([["Data","Ambiente","Periodicidade","Responsável","Conformidade","Situação"],row],`relatorio-checklist-${row[0].replaceAll("/", "-")}-${row[1].replaceAll(" ", "-")}.xls`)}
function downloadChecklistHistory(){downloadExcelTable([["Data","Ambiente","Periodicidade","Responsável","Conformidade","Situação"],...checklistHistory],"historico-de-checklists.xls")}
function historyPage(){return pageHeader("Histórico de checklists","Registros finalizados para acompanhamento e auditoria.",`<button class="btn" onclick="downloadChecklistHistory()">Baixar Excel</button>`)+`<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Ambiente</th><th>Periodicidade</th><th>Responsável</th><th>Conformidade</th><th>Situação</th><th>Relatório</th></tr></thead><tbody>${checklistHistory.map((r,index)=>`<tr>${r.map((x,i)=>`<td>${i===4?badge(x):i===5?badge(x):x}</td>`).join("")}<td><button class="btn" onclick="downloadChecklistReport(${index})">Baixar Excel</button></td></tr>`).join("")}</tbody></table></div></div>`}
function reportsPage(){return pageHeader("Relatórios e indicadores","Relatórios de checklist e manutenção por período, módulo, ambiente e responsável.",`<button class="btn primary" onclick="window.print()">Imprimir / PDF</button>`)+`<div class="card"><div class="toolbar"><input class="input" type="date" value="2026-08-01"><input class="input" type="date" value="2026-08-28"><select class="select"><option>Todos os módulos</option>${modules.map(m=>`<option>${m.name}</option>`).join("")}</select><button class="btn">Aplicar filtros</button></div></div><div class="grid three" style="margin-top:18px">${kpi("Total verificado","184","✓")}${kpi("Conformes","167","✓")}${kpi("Pendências","17","!")}</div><div class="grid two" style="margin-top:18px"><div class="card"><h3>Relatório de checklist</h3>${summaryLine("Período","01/08/2026 a 28/08/2026")}${summaryLine("Total verificado","184")}${summaryLine("Conformes","167 (90,8%)")}${summaryLine("Não conformes","17 (9,2%)")}${summaryLine("Pendências","5")}</div><div class="card"><h3>Relatório de manutenção</h3>${summaryLine("Ocorrências abertas","4")}${summaryLine("Ocorrências críticas","1")}${summaryLine("Resolvidas no período","18")}${summaryLine("Tempo médio","1,8 dia")}${summaryLine("Validadas","17")}</div></div>`}
function schedulePage(){return pageHeader("Programação de checklists","Agende rotinas diárias, semanais e mensais.",`<button class="btn primary">+ Programar checklist</button>`)+`<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Ambiente</th><th>Módulo</th><th>Periodicidade</th><th>Próxima execução</th><th>Responsável</th><th>Situação</th><th>Ações</th></tr></thead><tbody>${checklistSchedules.map((schedule,index)=>{let e=environments.find(environment=>environment.code===schedule.environmentCode);if(!e)return "";let pending=e.code==="OF-MAN";return `<tr><td>${e.name}</td><td>${e.module}</td><td>${e.period}</td><td>${pending?"01/09/2026":"30/08/2026"}</td><td>${e.responsible}</td><td>${badge(pending?"Pendente":"Programado")}</td><td><button class="btn" onclick="deleteChecklistSchedule(${index})">Excluir</button></td></tr>`}).join("")}</tbody></table></div></div>`}
function deleteChecklistSchedule(index){let schedule=checklistSchedules[index];if(!schedule)return;if(!confirm("Excluir esta programação de checklist?"))return;checklistSchedules.splice(index,1);save();render()}
function loansPage(){return pageHeader("Empréstimos e devoluções","Controle de ferramentas e equipamentos emprestados.",`<button class="btn primary">+ Novo empréstimo</button>`)+`<div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>Item</th><th>Quantidade</th><th>Retirada</th><th>Previsão</th><th>Devolução</th><th>Responsável</th><th>Situação</th><th>Ações</th></tr></thead><tbody>${loanRecords.map((loan,index)=>`<tr><td>${esc(loan.item)}</td><td>${esc(loan.quantity)}</td><td>${esc(loan.withdrawal)}</td><td>${esc(loan.due)}</td><td>${esc(loan.returnDate)}</td><td>${esc(loan.responsible)}</td><td>${badge(loan.status)}</td><td><button class="btn" onclick="openLoanEdit(${index})">Editar</button></td></tr>`).join("")}</tbody></table></div></div>`}
function openLoanEdit(index){let loan=loanRecords[index];if(!loan)return;showModal(`<div class="modal-head"><h3>Editar empréstimo</h3><button class="close" onclick="closeModal()">✕</button></div><div class="form-grid"><div class="field full"><label>Item</label><input class="input" id="editLoanItem" value="${esc(loan.item)}"></div><div class="field"><label>Quantidade</label><input class="input" id="editLoanQuantity" type="number" min="1" value="${esc(loan.quantity)}"></div><div class="field"><label>Responsável</label><input class="input" id="editLoanResponsible" value="${esc(loan.responsible)}"></div><div class="field"><label>Data de retirada</label><input class="input" id="editLoanWithdrawal" value="${esc(loan.withdrawal)}"></div><div class="field"><label>Previsão de devolução</label><input class="input" id="editLoanDue" value="${esc(loan.due)}"></div><div class="field"><label>Data de devolução</label><input class="input" id="editLoanReturn" value="${esc(loan.returnDate)}"></div><div class="field"><label>Situação</label><select class="select" id="editLoanStatus">${["Ativo","Atrasado","Devolvido","Cancelado"].map(status=>`<option ${status===loan.status?"selected":""}>${status}</option>`).join("")}</select></div></div><div style="display:flex;justify-content:flex-end;gap:10px;margin-top:18px"><button class="btn" onclick="closeModal()">Cancelar</button><button class="btn primary" onclick="saveLoanEdit(${index})">Salvar alterações</button></div>`)}
function saveLoanEdit(index){let loan=loanRecords[index];if(!loan)return;loan.item=document.getElementById("editLoanItem").value.trim()||loan.item;loan.quantity=document.getElementById("editLoanQuantity").value||loan.quantity;loan.responsible=document.getElementById("editLoanResponsible").value.trim()||loan.responsible;loan.withdrawal=document.getElementById("editLoanWithdrawal").value.trim();loan.due=document.getElementById("editLoanDue").value.trim();loan.returnDate=document.getElementById("editLoanReturn").value.trim()||"—";loan.status=document.getElementById("editLoanStatus").value;save();closeModal();render()}
function settingsPage(){return pageHeader("Configurações e auditoria","Regras de negócio, notificações e rastreabilidade.",`<button class="btn success" onclick="alert('Configurações salvas no protótipo.')">Salvar configurações</button>`)+`<div class="grid two"><div class="card"><h3>Regras de negócio</h3>${["Usuário só preenche ambientes designados","Não concluir checklist com itens sem resposta","Observação obrigatória em situações irregulares","Não conformidade gera ocorrência","Checklist finalizado não pode ser alterado pelo usuário comum","Saída do estoque não pode deixar saldo negativo","Abaixo do mínimo gera alerta","Encerramento exige validação do responsável"].map(x=>`<div class="list-item"><span>${x}</span><input type="checkbox" checked></div>`).join("")}</div><div class="card"><h3>Notificações</h3>${["Checklist liberado","Checklist próximo do vencimento","Checklist atrasado","Nova ocorrência","Ocorrência atribuída","Prazo vencido","Estoque abaixo do mínimo","Empréstimo próximo do vencimento","Empréstimo atrasado"].map(x=>`<div class="list-item"><span>${x}</span><input type="checkbox" checked></div>`).join("")}</div></div><div class="card" style="margin-top:18px"><h3>Auditoria</h3><p style="color:#6b7785;font-size:13px">Todas as correções relevantes devem permanecer registradas no histórico de auditoria.</p><div class="table-wrap"><table class="table"><thead><tr><th>Data/hora</th><th>Usuário</th><th>Ação</th><th>Registro</th></tr></thead><tbody><tr><td>28/08/2026 13:41</td><td>Administrador</td><td>Checklist finalizado</td><td>SA-101</td></tr><tr><td>28/08/2026 13:44</td><td>Manutenção</td><td>Ocorrência atualizada</td><td>OS-2026-0041</td></tr></tbody></table></div></div>`}
function page(){
 if(state.page==="dashboard")return dashboard(); if(state.page==="checklist")return checklistPage(); if(state.page==="maintenance")return maintenance(); if(state.page==="environments")return environmentsPage(); if(state.page==="stock")return stockPage(); if(state.page==="users")return usersPage(); if(state.page==="catalog")return catalogPage(); if(state.page==="history")return historyPage(); if(state.page==="reports")return reportsPage(); if(state.page==="schedule")return schedulePage(); if(state.page==="loans")return loansPage(); if(state.page==="settings")return settingsPage(); return dashboard();
}
function render(){if(!state.user){document.getElementById("app").innerHTML=`<div class="login"><div class="login-box"><div class="login-brand">SGA</div><h2>SGA-Checklist</h2><p>Sistema de Gerenciamento de Ambientes e Checklist Organizacional</p><div class="field"><label>E-mail</label><input class="input" id="loginEmail" value="admin@sga.local"></div><div class="field"><label>Senha</label><input class="input" id="loginPass" type="password" value="123456"></div><button class="btn primary" onclick="login()">Entrar</button><p style="text-align:center;margin-top:15px">Protótipo funcional • dados locais no navegador</p></div></div>`;return}document.getElementById("app").innerHTML=layout();document.getElementById("content").innerHTML=page()}
function login(){state.user={name:"Administrador",role:"Administrador",email:document.getElementById("loginEmail").value};save();render()}
function logout(){state.user=null;localStorage.removeItem("sga_user");render()}
render();
